name: Main

on: push

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # SDK Version to use; x will use the latest version of the 8.0 channel
      - if: runner.os == 'macOS'
        name: Remove Mono
        run: |
          sudo rm -rf /Library/Frameworks/Mono.framework
          sudo pkgutil --forget com.xamarin.mono-MDK.pkg
          sudo rm /etc/paths.d/mono-commands
      - name: Install dependencies
        run: npm i
      - name: Run Dotnet Build
        run: dotnet build src/QuickStart.sln
      - name: Run Core
        run: npm start
      - name: Run Standard
        run: npm run start:standard
